AWSTemplateFormatVersion: '2010-09-09'
Description: Full Stack EC2 PoC (VPC, IGW, RouteTable, EC2) - Dynamic Naming

# ============================================================
# Metadata: コンソール表示をわかりやすくするための設定
# ============================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "① Server Configuration (サーバー設定)"
        Parameters:
          - TargetAZ       
          - OsVersion
          - InstanceType
      - Label: 
          default: "② Access & Security (アクセス権限)"
        Parameters:
          - KeyName
          - MyIpAddress
    ParameterLabels:
      TargetAZ:
        default: "Target Availability Zone" 
      OsVersion:
        default: "OS Version (Amazon Linux)"
      InstanceType:
        default: "Instance Type (Spec)"
      KeyName:
        default: "SSH Key Pair Name"
      MyIpAddress:
        default: "Allowed SSH IP (CIDR)"

# ============================================================
# Parameters: 選択肢の定義
# ============================================================
Parameters:
  # ▼▼▼ 追加: AZを選択するパラメータ ▼▼▼
  TargetAZ:
    Description: Select the Availability Zone (e.g., ap-northeast-1a).
    Type: AWS::EC2::AvailabilityZone::Name
  # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

  OsVersion:
    Type: String
    Default: AmazonLinux2
    AllowedValues:
      - AmazonLinux2023
      - AmazonLinux2
    Description: Select the OS version.

  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - m5.large
    Description: Select EC2 instance type.

  KeyName:
    Description: Select an existing EC2 KeyPair for SSH access.
    Type: AWS::EC2::KeyPair::KeyName

  MyIpAddress:
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    Description: IP address range allowed to SSH to the instance.

# ------------------------------------------------------------
# Conditions
# ------------------------------------------------------------
Conditions:
  IsAmazonLinux2: !Equals [ !Ref OsVersion, "AmazonLinux2" ]

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  # --- Network Layer ---
  PoCVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc"

  PoCIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-igw"

  PoCIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PoCVPC
      InternetGatewayId: !Ref PoCIGW

  PoCSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PoCVPC
      CidrBlock: 10.0.1.0/24
      # ▼▼▼ 修正: 自動選択ではなく、パラメータで選んだAZを使用 ▼▼▼
      AvailabilityZone: !Ref TargetAZ 
      # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-subnet"

  PoCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PoCVPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-rtb"

  PoCRoute:
    Type: AWS::EC2::Route
    DependsOn: PoCIGWAttachment
    Properties:
      RouteTableId: !Ref PoCRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PoCIGW

  PoCSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PoCSubnet
      RouteTableId: !Ref PoCRouteTable

  # --- Security Layer ---
  PoCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Allow SSH for ${AWS::StackName}"
      GroupName: !Sub "${AWS::StackName}-sg"
      VpcId: !Ref PoCVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIpAddress
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"

  # --- Compute Layer ---
  PoCInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !If 
        - IsAmazonLinux2
        - !Resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
        - !Resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      # ▼▼▼ 修正: AZを明示的に指定（Subnet経由で決まりますが念のため） ▼▼▼
      AvailabilityZone: !Ref TargetAZ
      # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: 
            - !Ref PoCSecurityGroup
          SubnetId: !Ref PoCSubnet
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y || yum update -y
          rpm -q dnf && TOOL=dnf || TOOL=yum
          $TOOL install -y git jq
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ec2"
        - Key: OS
          Value: !Ref OsVersion
        - Key: Environment
          Value: PoC

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  InstanceId:
    Value: !Ref PoCInstance
  PublicIP:
    Description: SSH Target IP
    Value: !GetAtt PoCInstance.PublicIp
  AvailabilityZone:
    Description: Deployed AZ
    Value: !GetAtt PoCInstance.AvailabilityZone
  SSHCommand:
    Description: Copy this command to connect
    Value: !Sub "ssh -i ${KeyName}.pem ec2-user@${PoCInstance.PublicIp}"