AWSTemplateFormatVersion: '2010-09-09'
Description: Full Stack EC2 PoC (Auto KeyPair & SSM Access)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "① Server Configuration"
        Parameters:
          - TargetAZ       
          - OsVersion
          - InstanceType
      - Label: 
          default: "② Access & Security"
        Parameters:
          # KeyName は自動生成するので削除しました
          - AllowedCidr
    ParameterLabels:
      TargetAZ:
        default: "Target Availability Zone" 
      AllowedCidr:
        default: "SSH Allowed CIDR"

Parameters:
  TargetAZ:
    Description: Select the Availability Zone.
    Type: AWS::EC2::AvailabilityZone::Name
  
  OsVersion:
    Type: String
    Default: AmazonLinux2
    AllowedValues:
      - AmazonLinux2023
      - AmazonLinux2
    Description: Select the OS version.

  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: Select EC2 instance type.

  AllowedCidr:
    Type: String
    # ▼ ここをVPCのCIDR(10.0.0.0/16)にすると、外部からSSHできなくなります
    #   その代わり、Session Managerで接続できるようにIAMを設定します。
    Default: 10.0.0.0/16
    Description: IP range allowed for SSH (22). If restricted, use Session Manager.

Conditions:
  IsAmazonLinux2: !Equals [ !Ref OsVersion, "AmazonLinux2" ]

Resources:
  # ============================================================
  # 1. Key Pair (自動生成・スタック削除時に消える)
  # ============================================================
  PoCKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub "${AWS::StackName}-key"
      KeyType: rsa
      KeyFormat: pem

  # ============================================================
  # 2. Network Layer
  # ============================================================
  PoCVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc"

  PoCIGW:
    Type: AWS::EC2::InternetGateway

  PoCIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PoCVPC
      InternetGatewayId: !Ref PoCIGW

  PoCSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PoCVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Ref TargetAZ 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-subnet"

  PoCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PoCVPC

  PoCRoute:
    Type: AWS::EC2::Route
    DependsOn: PoCIGWAttachment
    Properties:
      RouteTableId: !Ref PoCRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PoCIGW

  PoCSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PoCSubnet
      RouteTableId: !Ref PoCRouteTable

  # ============================================================
  # 3. Security Layer
  # ============================================================
  PoCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Outbound
      VpcId: !Ref PoCVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCidr
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"

  # ============================================================
  # 4. IAM Role for Session Manager (SSH不要で接続するための権限)
  # ============================================================
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ssm-role"

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMRole

  # ============================================================
  # 5. Compute Layer
  # ============================================================
  PoCInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !If 
        - IsAmazonLinux2
        - '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
        - '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      InstanceType: !Ref InstanceType
      KeyName: !Ref PoCKeyPair
      IamInstanceProfile: !Ref SSMInstanceProfile # SSM権限を追加
      AvailabilityZone: !Ref TargetAZ
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: 
            - !Ref PoCSecurityGroup
          SubnetId: !Ref PoCSubnet
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y || yum update -y
          rpm -q dnf && TOOL=dnf || TOOL=yum
          $TOOL install -y git jq
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ec2"

Outputs:
  InstanceId:
    Value: !Ref PoCInstance
  ConnectWithSSM:
    Description: Click this link to connect (No SSH Key needed)
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/systems-manager/session-manager/${PoCInstance}"
  KeyParameterStoreName:
    Description: Private Key is stored here (SSM Parameter Store)
    Value: !Sub "/ec2/keypair/${PoCKeyPair}"